### ISSUE TITLE
Unable to Launch - Release 2024-04-25

### ISSUE THREAD

**Issue by tangomike99** [irixaligned/duckstation-uwp#3]
### Game details

N/A

### Description of the issue/bug

I understand that this project is planning to "go dark" with the latest release.

After uninstalling and re-installing the application with dependencies on my Xbox Series X, the Duckstation-UWP fails to launch. Sometimes it shows the splash logo. Most times it does not. The application appears to immediately crash on start.

I have reverted back to Release 2024-03-09, which continues to work as expected.

### Steps to reproduce

1. Uninstall any prior versions of Duckstation-UWP.
2. Install the [2024-04-25 release](https://github.com/irixaligned/duckstation-uwp/releases/tag/2024-04-25) using the Xbox Device Portal, including the dependency package.
3. Attempt to launch the application.
4. Note that you are immediately brought back to the Xbox home.

### Software and hardware information

Xbox Series X 10.0.25398.4086

### DuckStation version

Release 2024-04-25: "Misc: Remove unused code"

### DuckStation rendering backend

Direct3D 12

### DuckStation controller backend, drivers and wrappers

N/A

**Comment by irixaligned** [comment]
Hi.

First of all, thank you for formatting this issue so nicely.
I discovered this in the middle of getting ready to kill this GitHub account.

I released the last release too soon, as I was unable to test/debug on Xbox, and when I requested help, unfortunately people who were working with me weren't able to debug themselves before I was incapable of working on the project. I had already delivered the release and wrote the notes, though, and it was impractical to pull it back at that point in time, so I set it to pre-release and unpinned it.

As such, the build only works on Windows 10, and the reason is unknown. I apologize sincerely for this, but it will not be fixed. I simply cannot debug this, due to personal troubles out of my control.

Sorry that the last release is broken, I just didn't know and couldn't fix it in time. The code available is still the code for the latest build, so if you have any debugging experience, you are welcome to fix it yourself and make a PR. I'll keep this account up for a week more to merge that in if it happens.

Again, really sorry about this. Life's gotten to me and I don't have much of a choice here.
